name: Build release zip (save on Github)

on:
    push:
        tags:
            - 'v*'
    pull_request:
        tags:
            - "v*" 

jobs:
    tag:
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build plugin # Remove or modify this step as needed
              run: |
                  npm install
                  npm run build
                  npm run plugin-zip

            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: WordPress Plugin Deploy
              uses: nk-o/action-wordpress-plugin-deploy@master
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SOURCE_DIR: dist/
                  SLUG: carbonbadge-block